export const ADD_FLASH_MESSAGE = "ADD_FLASH_MESSAGE"
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const RECEIVE_PROPERTIES = 'RECEIVE_PROPERTIES'
export const FETCH_PROPERTIES_ERROR = 'FETCH_PROPERTIES_ERROR'
export const SET_OVERALL_PROPERTIES = 'SET_OVERALL_PROPERTIES'
export const RECEIVE_PAYMENTS = 'RECEIVE_PAYMENTS'
export const SET_CURRENT_PROPERTY = 'SET_CURRENT_PROPERTY'